primer_nombre = input("Ingrese su primer nombre: ")
segundo_nombre = input("Ingrese su segundo nombre: ")
primer_apellido = input("Ingrese su primer apellido: ")
segundo_apellido = input("Ingrese su segundo apellido: ")
edad = input("Ingrese su edad: ")
anio_nacimiento = input("Ingrese su año de nacimiento: ")

print("\n--- INFORMACIÓN DEL USUARIO ---")
print(f"Nombre completo: {primer_nombre} {segundo_nombre} {primer_apellido} {segundo_apellido}")
print(f"Edad: {edad} años")
print(f"Año de nacimiento: {anio_nacimiento}")